/********************************************************************************
** Form generated from reading UI file 'configurer.ui'
**
** Created
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONFIGURER_H
#define UI_CONFIGURER_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLayout>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QTextEdit>
#include <QtGui/QToolBox>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Configurer
{
public:
    QWidget *centralwidget;
    QTabWidget *tabWidget;
    QWidget *tab_6;
    QPushButton *btAffLog;
    QPushButton *btSuppLog;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QTextEdit *txtLog;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_35;
    QLabel *label_36;
    QFrame *line;
    QFrame *line_2;
    QWidget *tab;
    QToolBox *tBoxLier;
    QWidget *page;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *lEditNumBadgeLier;
    QLineEdit *lEditDateServiceLier;
    QLineEdit *lEditDatePileLier;
    QTextEdit *txtBadgeExistant;
    QPushButton *btBadgeExistant;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QPushButton *btOkLier;
    QPushButton *btAnnulerLier;
    QLabel *label_8;
    QLabel *label_39;
    QComboBox *cBoxPersonneLier;
    QLabel *label_40;
    QTextEdit *txtInfoPersonne;
    QWidget *page_2;
    QLabel *label_19;
    QComboBox *cBoxLierMod;
    QLabel *label_20;
    QLineEdit *lEditNumBadgeMod;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *lEditDateServiceMod;
    QLineEdit *lEditDatePileMod;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QPushButton *btAnnulerLierMod;
    QPushButton *btOkLierMod;
    QLabel *label_31;
    QLabel *label_37;
    QLabel *label_42;
    QTextEdit *txtInfoBadgeLier;
    QLabel *label_34;
    QTextEdit *txtBadgeExistant_2;
    QLabel *label_23;
    QPushButton *btBadgeExistant_2;
    QWidget *page_3;
    QLabel *label_29;
    QComboBox *cBoxBadgeSupp;
    QLabel *label_30;
    QTextEdit *txtInfoBadgeDelier;
    QPushButton *btAnnulerDelier;
    QPushButton *btOkDelier;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_38;
    QLabel *label_41;
    QTextEdit *txtInfoPersonneDelier;
    QWidget *tab_2;
    QToolBox *tBoxConfigLecteur_2;
    QWidget *page_10;
    QWidget *page_11;
    QWidget *page_12;
    QWidget *tab_4;
    QToolBox *tBoxConfigLecteur;
    QWidget *page_4;
    QWidget *page_5;
    QWidget *page_6;
    QWidget *tab_5;
    QToolBox *tBoxConfigSuper;
    QWidget *page_7;
    QWidget *page_8;
    QWidget *page_9;
    QWidget *page_13;
    QPushButton *btAffichage;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *Configurer)
    {
        if (Configurer->objectName().isEmpty())
            Configurer->setObjectName(QString::fromUtf8("Configurer"));
        Configurer->resize(920, 640);
        centralwidget = new QWidget(Configurer);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setEnabled(true);
        tabWidget->setGeometry(QRect(0, 40, 920, 590));
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        btAffLog = new QPushButton(tab_6);
        btAffLog->setObjectName(QString::fromUtf8("btAffLog"));
        btAffLog->setGeometry(QRect(70, 30, 170, 30));
        btSuppLog = new QPushButton(tab_6);
        btSuppLog->setObjectName(QString::fromUtf8("btSuppLog"));
        btSuppLog->setGeometry(QRect(550, 30, 170, 30));
        label = new QLabel(tab_6);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(735, 30, 141, 16));
        label->setTextFormat(Qt::AutoText);
        label_2 = new QLabel(tab_6);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(732, 50, 141, 16));
        label_2->setTextFormat(Qt::AutoText);
        label_3 = new QLabel(tab_6);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(710, 70, 201, 16));
        label_4 = new QLabel(tab_6);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(765, 10, 71, 16));
        QFont font;
        font.setBold(true);
        font.setUnderline(true);
        font.setWeight(75);
        label_4->setFont(font);
        txtLog = new QTextEdit(tab_6);
        txtLog->setObjectName(QString::fromUtf8("txtLog"));
        txtLog->setGeometry(QRect(0, 130, 911, 421));
        label_5 = new QLabel(tab_6);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(255, 30, 121, 16));
        label_5->setTextFormat(Qt::AutoText);
        label_6 = new QLabel(tab_6);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(252, 50, 141, 16));
        label_6->setTextFormat(Qt::AutoText);
        label_7 = new QLabel(tab_6);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(250, 70, 141, 16));
        label_35 = new QLabel(tab_6);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(480, 10, 51, 61));
        label_35->setPixmap(QPixmap(QString::fromUtf8("../ressources/poubelle.png")));
        label_36 = new QLabel(tab_6);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(10, 10, 51, 61));
        label_36->setPixmap(QPixmap(QString::fromUtf8("../ressources/historique.png")));
        line = new QFrame(tab_6);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(450, 10, 20, 101));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(tab_6);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(7, 110, 901, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        tabWidget->addTab(tab_6, QString());
        label_35->raise();
        btAffLog->raise();
        btSuppLog->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        txtLog->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_36->raise();
        line->raise();
        line_2->raise();
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tBoxLier = new QToolBox(tab);
        tBoxLier->setObjectName(QString::fromUtf8("tBoxLier"));
        tBoxLier->setGeometry(QRect(10, 10, 900, 530));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        page->setGeometry(QRect(0, 0, 100, 30));
        label_9 = new QLabel(page);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 0, 421, 16));
        label_10 = new QLabel(page);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(60, 30, 121, 16));
        label_10->setFont(font);
        label_11 = new QLabel(page);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(60, 100, 181, 16));
        label_11->setFont(font);
        label_12 = new QLabel(page);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(60, 170, 211, 16));
        label_12->setFont(font);
        lEditNumBadgeLier = new QLineEdit(page);
        lEditNumBadgeLier->setObjectName(QString::fromUtf8("lEditNumBadgeLier"));
        lEditNumBadgeLier->setGeometry(QRect(80, 50, 160, 22));
        lEditDateServiceLier = new QLineEdit(page);
        lEditDateServiceLier->setObjectName(QString::fromUtf8("lEditDateServiceLier"));
        lEditDateServiceLier->setGeometry(QRect(80, 120, 160, 22));
        lEditDatePileLier = new QLineEdit(page);
        lEditDatePileLier->setObjectName(QString::fromUtf8("lEditDatePileLier"));
        lEditDatePileLier->setGeometry(QRect(80, 190, 160, 22));
        txtBadgeExistant = new QTextEdit(page);
        txtBadgeExistant->setObjectName(QString::fromUtf8("txtBadgeExistant"));
        txtBadgeExistant->setEnabled(true);
        txtBadgeExistant->setGeometry(QRect(370, 70, 331, 31));
        txtBadgeExistant->viewport()->setProperty("cursor", QVariant(QCursor(Qt::ForbiddenCursor)));
        txtBadgeExistant->setReadOnly(true);
        btBadgeExistant = new QPushButton(page);
        btBadgeExistant->setObjectName(QString::fromUtf8("btBadgeExistant"));
        btBadgeExistant->setGeometry(QRect(260, 70, 111, 23));
        label_13 = new QLabel(page);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(250, 30, 381, 16));
        QFont font1;
        font1.setItalic(true);
        label_13->setFont(font1);
        label_14 = new QLabel(page);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(250, 50, 581, 16));
        label_15 = new QLabel(page);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(260, 120, 381, 16));
        label_15->setFont(font1);
        label_16 = new QLabel(page);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(260, 140, 561, 16));
        label_17 = new QLabel(page);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(260, 190, 381, 16));
        label_17->setFont(font1);
        label_18 = new QLabel(page);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(260, 210, 561, 16));
        btOkLier = new QPushButton(page);
        btOkLier->setObjectName(QString::fromUtf8("btOkLier"));
        btOkLier->setGeometry(QRect(630, 400, 100, 30));
        QIcon icon;
        icon.addFile(QString::fromUtf8("../ressources/bt_ok.png"), QSize(), QIcon::Normal, QIcon::Off);
        btOkLier->setIcon(icon);
        btAnnulerLier = new QPushButton(page);
        btAnnulerLier->setObjectName(QString::fromUtf8("btAnnulerLier"));
        btAnnulerLier->setGeometry(QRect(520, 400, 100, 30));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("../ressources/ButtonClose.png"), QSize(), QIcon::Normal, QIcon::Off);
        btAnnulerLier->setIcon(icon1);
        label_8 = new QLabel(page);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(840, 0, 51, 51));
        label_8->setPixmap(QPixmap(QString::fromUtf8("../ressources/new.png")));
        label_39 = new QLabel(page);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(10, 250, 321, 16));
        cBoxPersonneLier = new QComboBox(page);
        cBoxPersonneLier->setObjectName(QString::fromUtf8("cBoxPersonneLier"));
        cBoxPersonneLier->setGeometry(QRect(350, 245, 190, 23));
        label_40 = new QLabel(page);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(60, 290, 281, 16));
        label_40->setFont(font);
        txtInfoPersonne = new QTextEdit(page);
        txtInfoPersonne->setObjectName(QString::fromUtf8("txtInfoPersonne"));
        txtInfoPersonne->setGeometry(QRect(80, 320, 451, 71));
        txtInfoPersonne->viewport()->setProperty("cursor", QVariant(QCursor(Qt::ForbiddenCursor)));
        txtInfoPersonne->setReadOnly(true);
        tBoxLier->addItem(page, QString::fromUtf8("Lier un Badge \303\240 une Personne"));
        label_8->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        lEditNumBadgeLier->raise();
        lEditDateServiceLier->raise();
        lEditDatePileLier->raise();
        txtBadgeExistant->raise();
        btBadgeExistant->raise();
        label_13->raise();
        label_14->raise();
        label_15->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        btOkLier->raise();
        btAnnulerLier->raise();
        label_39->raise();
        cBoxPersonneLier->raise();
        label_40->raise();
        txtInfoPersonne->raise();
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        page_2->setGeometry(QRect(0, 0, 890, 442));
        label_19 = new QLabel(page_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(20, 30, 341, 16));
        cBoxLierMod = new QComboBox(page_2);
        cBoxLierMod->setObjectName(QString::fromUtf8("cBoxLierMod"));
        cBoxLierMod->setEnabled(true);
        cBoxLierMod->setGeometry(QRect(380, 30, 131, 23));
        label_20 = new QLabel(page_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(50, 170, 121, 16));
        label_20->setFont(font);
        lEditNumBadgeMod = new QLineEdit(page_2);
        lEditNumBadgeMod->setObjectName(QString::fromUtf8("lEditNumBadgeMod"));
        lEditNumBadgeMod->setGeometry(QRect(70, 190, 160, 22));
        label_21 = new QLabel(page_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(50, 240, 181, 16));
        label_21->setFont(font);
        label_22 = new QLabel(page_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(50, 310, 211, 16));
        label_22->setFont(font);
        lEditDateServiceMod = new QLineEdit(page_2);
        lEditDateServiceMod->setObjectName(QString::fromUtf8("lEditDateServiceMod"));
        lEditDateServiceMod->setGeometry(QRect(70, 260, 160, 22));
        lEditDatePileMod = new QLineEdit(page_2);
        lEditDatePileMod->setObjectName(QString::fromUtf8("lEditDatePileMod"));
        lEditDatePileMod->setGeometry(QRect(70, 330, 160, 22));
        label_24 = new QLabel(page_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(20, 150, 581, 16));
        label_25 = new QLabel(page_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(250, 260, 381, 16));
        label_25->setFont(font1);
        label_26 = new QLabel(page_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(250, 280, 561, 16));
        label_27 = new QLabel(page_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(250, 330, 381, 16));
        label_27->setFont(font1);
        label_28 = new QLabel(page_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(250, 350, 561, 16));
        btAnnulerLierMod = new QPushButton(page_2);
        btAnnulerLierMod->setObjectName(QString::fromUtf8("btAnnulerLierMod"));
        btAnnulerLierMod->setGeometry(QRect(520, 400, 100, 30));
        btAnnulerLierMod->setIcon(icon1);
        btOkLierMod = new QPushButton(page_2);
        btOkLierMod->setObjectName(QString::fromUtf8("btOkLierMod"));
        btOkLierMod->setGeometry(QRect(630, 400, 100, 30));
        btOkLierMod->setIcon(icon);
        label_31 = new QLabel(page_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(520, 30, 281, 16));
        label_37 = new QLabel(page_2);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(840, 0, 51, 51));
        label_37->setPixmap(QPixmap(QString::fromUtf8("../ressources/modifier.png")));
        label_42 = new QLabel(page_2);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(50, 50, 241, 16));
        label_42->setFont(font);
        txtInfoBadgeLier = new QTextEdit(page_2);
        txtInfoBadgeLier->setObjectName(QString::fromUtf8("txtInfoBadgeLier"));
        txtInfoBadgeLier->setGeometry(QRect(70, 70, 451, 71));
        label_34 = new QLabel(page_2);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(250, 180, 381, 16));
        label_34->setFont(font1);
        txtBadgeExistant_2 = new QTextEdit(page_2);
        txtBadgeExistant_2->setObjectName(QString::fromUtf8("txtBadgeExistant_2"));
        txtBadgeExistant_2->setEnabled(true);
        txtBadgeExistant_2->setGeometry(QRect(370, 220, 331, 31));
        txtBadgeExistant_2->viewport()->setProperty("cursor", QVariant(QCursor(Qt::ForbiddenCursor)));
        txtBadgeExistant_2->setReadOnly(true);
        label_23 = new QLabel(page_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(250, 200, 581, 16));
        btBadgeExistant_2 = new QPushButton(page_2);
        btBadgeExistant_2->setObjectName(QString::fromUtf8("btBadgeExistant_2"));
        btBadgeExistant_2->setGeometry(QRect(260, 220, 111, 23));
        tBoxLier->addItem(page_2, QString::fromUtf8("Apporter une modification concernant une Affectation"));
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        page_3->setGeometry(QRect(0, 0, 100, 30));
        label_29 = new QLabel(page_3);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 0, 341, 16));
        cBoxBadgeSupp = new QComboBox(page_3);
        cBoxBadgeSupp->setObjectName(QString::fromUtf8("cBoxBadgeSupp"));
        cBoxBadgeSupp->setGeometry(QRect(370, 0, 131, 23));
        label_30 = new QLabel(page_3);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(50, 130, 241, 16));
        label_30->setFont(font);
        txtInfoBadgeDelier = new QTextEdit(page_3);
        txtInfoBadgeDelier->setObjectName(QString::fromUtf8("txtInfoBadgeDelier"));
        txtInfoBadgeDelier->setGeometry(QRect(50, 150, 451, 71));
        btAnnulerDelier = new QPushButton(page_3);
        btAnnulerDelier->setObjectName(QString::fromUtf8("btAnnulerDelier"));
        btAnnulerDelier->setGeometry(QRect(520, 400, 100, 30));
        btAnnulerDelier->setIcon(icon1);
        btOkDelier = new QPushButton(page_3);
        btOkDelier->setObjectName(QString::fromUtf8("btOkDelier"));
        btOkDelier->setGeometry(QRect(630, 400, 100, 30));
        btOkDelier->setIcon(icon);
        label_32 = new QLabel(page_3);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(60, 50, 381, 16));
        label_32->setFont(font);
        label_33 = new QLabel(page_3);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(80, 70, 151, 16));
        label_38 = new QLabel(page_3);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(840, 0, 51, 51));
        label_38->setPixmap(QPixmap(QString::fromUtf8("../ressources/supprimer.png")));
        label_41 = new QLabel(page_3);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(50, 240, 421, 16));
        label_41->setFont(font);
        txtInfoPersonneDelier = new QTextEdit(page_3);
        txtInfoPersonneDelier->setObjectName(QString::fromUtf8("txtInfoPersonneDelier"));
        txtInfoPersonneDelier->setGeometry(QRect(50, 260, 451, 71));
        tBoxLier->addItem(page_3, QString::fromUtf8("D\303\251saffecter un Badge \303\240 une Personne"));
        label_38->raise();
        label_29->raise();
        cBoxBadgeSupp->raise();
        label_30->raise();
        txtInfoBadgeDelier->raise();
        btAnnulerDelier->raise();
        btOkDelier->raise();
        label_32->raise();
        label_33->raise();
        label_41->raise();
        txtInfoPersonneDelier->raise();
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tBoxConfigLecteur_2 = new QToolBox(tab_2);
        tBoxConfigLecteur_2->setObjectName(QString::fromUtf8("tBoxConfigLecteur_2"));
        tBoxConfigLecteur_2->setGeometry(QRect(10, 30, 970, 380));
        page_10 = new QWidget();
        page_10->setObjectName(QString::fromUtf8("page_10"));
        page_10->setGeometry(QRect(0, 0, 960, 292));
        tBoxConfigLecteur_2->addItem(page_10, QString::fromUtf8("Ajouter une nouvelle Personne"));
        page_11 = new QWidget();
        page_11->setObjectName(QString::fromUtf8("page_11"));
        page_11->setGeometry(QRect(0, 0, 100, 30));
        tBoxConfigLecteur_2->addItem(page_11, QString::fromUtf8("Modifier une Personne existante"));
        page_12 = new QWidget();
        page_12->setObjectName(QString::fromUtf8("page_12"));
        page_12->setGeometry(QRect(0, 0, 100, 30));
        tBoxConfigLecteur_2->addItem(page_12, QString::fromUtf8("Effacer une Personne existante"));
        tabWidget->addTab(tab_2, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        tBoxConfigLecteur = new QToolBox(tab_4);
        tBoxConfigLecteur->setObjectName(QString::fromUtf8("tBoxConfigLecteur"));
        tBoxConfigLecteur->setGeometry(QRect(10, 30, 970, 380));
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        page_4->setGeometry(QRect(0, 0, 960, 292));
        tBoxConfigLecteur->addItem(page_4, QString::fromUtf8("Ajouter un nouveau Lecteur"));
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        page_5->setGeometry(QRect(0, 0, 100, 30));
        tBoxConfigLecteur->addItem(page_5, QString::fromUtf8("Modifier un Lecteur existant"));
        page_6 = new QWidget();
        page_6->setObjectName(QString::fromUtf8("page_6"));
        page_6->setGeometry(QRect(0, 0, 100, 30));
        tBoxConfigLecteur->addItem(page_6, QString::fromUtf8("Effacer un Lecteur existant"));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        tBoxConfigSuper = new QToolBox(tab_5);
        tBoxConfigSuper->setObjectName(QString::fromUtf8("tBoxConfigSuper"));
        tBoxConfigSuper->setGeometry(QRect(10, 30, 970, 380));
        page_7 = new QWidget();
        page_7->setObjectName(QString::fromUtf8("page_7"));
        page_7->setGeometry(QRect(0, 0, 100, 30));
        tBoxConfigSuper->addItem(page_7, QString::fromUtf8("Gestion des Vues"));
        page_8 = new QWidget();
        page_8->setObjectName(QString::fromUtf8("page_8"));
        page_8->setGeometry(QRect(0, 0, 100, 30));
        tBoxConfigSuper->addItem(page_8, QString::fromUtf8("Gestions des Lieux"));
        page_9 = new QWidget();
        page_9->setObjectName(QString::fromUtf8("page_9"));
        page_9->setGeometry(QRect(0, 0, 100, 30));
        tBoxConfigSuper->addItem(page_9, QString::fromUtf8("Gestion des Zones"));
        page_13 = new QWidget();
        page_13->setObjectName(QString::fromUtf8("page_13"));
        page_13->setGeometry(QRect(0, 0, 960, 266));
        tBoxConfigSuper->addItem(page_13, QString::fromUtf8("Gestion des Timers"));
        tabWidget->addTab(tab_5, QString());
        btAffichage = new QPushButton(centralwidget);
        btAffichage->setObjectName(QString::fromUtf8("btAffichage"));
        btAffichage->setGeometry(QRect(764, 10, 141, 23));
        Configurer->setCentralWidget(centralwidget);
        menubar = new QMenuBar(Configurer);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 920, 20));
        Configurer->setMenuBar(menubar);
        statusbar = new QStatusBar(Configurer);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        Configurer->setStatusBar(statusbar);

        retranslateUi(Configurer);

        tabWidget->setCurrentIndex(1);
        tBoxLier->setCurrentIndex(1);
        tBoxConfigLecteur_2->setCurrentIndex(0);
        tBoxConfigLecteur->setCurrentIndex(0);
        tBoxConfigSuper->setCurrentIndex(3);


        QMetaObject::connectSlotsByName(Configurer);
    } // setupUi

    void retranslateUi(QMainWindow *Configurer)
    {
        Configurer->setWindowTitle(QApplication::translate("Configurer", "MainWindow", 0, QApplication::UnicodeUTF8));
        btAffLog->setText(QApplication::translate("Configurer", "Obtenir l'Historique", 0, QApplication::UnicodeUTF8));
        btSuppLog->setText(QApplication::translate("Configurer", "Vider l'Historique", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("Configurer", "Cette action entraine", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("Configurer", "une suppression totale", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("Configurer", "de l'Historique des \303\251v\303\251nements.", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("Configurer", "Attention", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("Configurer", "Cette action permet", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("Configurer", "d'obtenir l'Historique", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("Configurer", "des \303\251v\303\251nements (Log).", 0, QApplication::UnicodeUTF8));
        label_35->setText(QString());
        label_36->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QApplication::translate("Configurer", "Historique des \303\251v\303\251nements", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("Configurer", "Remplir les champs ci-dessous pour ajouter un nouveau badge :", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("Configurer", "Num\303\251ro du badge :", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("Configurer", "Date de Mise en Service :", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("Configurer", "Date de Changement de Pile :", 0, QApplication::UnicodeUTF8));
        btBadgeExistant->setText(QApplication::translate("Configurer", "Badge existant", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("Configurer", "Attention \303\240 ne pas mettre un num\303\251ro de badge d\303\251j\303\240 existant !", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("Configurer", "Cliquer sur le bouton ci-dessous pour obtenir une liste des num\303\251ros de badges d\303\251j\303\240 existants :", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("Configurer", "Mettre sous la forme AAAA-MM-JJ", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("Configurer", "Vous pouvez indiquer la date d'aujourd'hui ou mettre 0000-00-00.", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("Configurer", "Mettre sous la forme AAAA-MM-JJ", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("Configurer", "Vous pouvez indiquer la date approximative de changement de pile ou mettre 0000-00-00.", 0, QApplication::UnicodeUTF8));
        btOkLier->setText(QApplication::translate("Configurer", "Confirmer", 0, QApplication::UnicodeUTF8));
        btAnnulerLier->setText(QApplication::translate("Configurer", "Annuler", 0, QApplication::UnicodeUTF8));
        label_8->setText(QString());
        label_39->setText(QApplication::translate("Configurer", "Choisir ci-contre la Personne \303\240 lier \303\240 ce badge :", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("Configurer", "Information concernant cette Personne :", 0, QApplication::UnicodeUTF8));
        tBoxLier->setItemText(tBoxLier->indexOf(page), QApplication::translate("Configurer", "Lier un Badge \303\240 une Personne", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("Configurer", "Choissir un badge dans la liste d\303\251roulante ci-contre :", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("Configurer", "Num\303\251ro du badge :", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("Configurer", "Date de Mise en Service :", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("Configurer", "Date de Changement de Pile :", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("Configurer", "Apporter vos modifications directements dans les champs ci-dessous, puis Confirmer", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("Configurer", "Mettre sous la forme AAAA-MM-JJ", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("Configurer", "Vous pouvez indiquer la date d'aujourd'hui ou mettre 0000-00-00.", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("Configurer", "Mettre sous la forme AAAA-MM-JJ", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("Configurer", "Vous pouvez indiquer la date approximative de changement de pile ou mettre 0000-00-00.", 0, QApplication::UnicodeUTF8));
        btAnnulerLierMod->setText(QApplication::translate("Configurer", "Annuler", 0, QApplication::UnicodeUTF8));
        btOkLierMod->setText(QApplication::translate("Configurer", "Confirmer", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("Configurer", "Apparaissent uniquement les badges inactifs.", 0, QApplication::UnicodeUTF8));
        label_37->setText(QString());
        label_42->setText(QApplication::translate("Configurer", "Information concernant ce badge :", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("Configurer", "Indiquer obligatoirement un nombre positif", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("Configurer", "Cliquer sur le bouton ci-dessous pour obtenir une liste des num\303\251ros de badges d\303\251j\303\240 existants :", 0, QApplication::UnicodeUTF8));
        btBadgeExistant_2->setText(QApplication::translate("Configurer", "Badge existant", 0, QApplication::UnicodeUTF8));
        tBoxLier->setItemText(tBoxLier->indexOf(page_2), QApplication::translate("Configurer", "Apporter une modification concernant une Affectation", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("Configurer", "Choissir un badge dans la liste d\303\251roulante ci-contre :", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("Configurer", "Information concernant ce badge :", 0, QApplication::UnicodeUTF8));
        btAnnulerDelier->setText(QApplication::translate("Configurer", "Annuler", 0, QApplication::UnicodeUTF8));
        btOkDelier->setText(QApplication::translate("Configurer", "Confirmer", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("Configurer", "Attention il n'est pas possible de supprimer un badge :", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("Configurer", "-> Si le badge est actif", 0, QApplication::UnicodeUTF8));
        label_38->setText(QString());
        label_41->setText(QApplication::translate("Configurer", "Information concernant la Personne qui est li\303\251e \303\240 ce Badge :", 0, QApplication::UnicodeUTF8));
        tBoxLier->setItemText(tBoxLier->indexOf(page_3), QApplication::translate("Configurer", "D\303\251saffecter un Badge \303\240 une Personne", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("Configurer", "Affecter/D\303\251saffecter Badge \303\240 une Personne", 0, QApplication::UnicodeUTF8));
        tBoxConfigLecteur_2->setItemText(tBoxConfigLecteur_2->indexOf(page_10), QApplication::translate("Configurer", "Ajouter une nouvelle Personne", 0, QApplication::UnicodeUTF8));
        tBoxConfigLecteur_2->setItemText(tBoxConfigLecteur_2->indexOf(page_11), QApplication::translate("Configurer", "Modifier une Personne existante", 0, QApplication::UnicodeUTF8));
        tBoxConfigLecteur_2->setItemText(tBoxConfigLecteur_2->indexOf(page_12), QApplication::translate("Configurer", "Effacer une Personne existante", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("Configurer", "Configurer Personne", 0, QApplication::UnicodeUTF8));
        tBoxConfigLecteur->setItemText(tBoxConfigLecteur->indexOf(page_4), QApplication::translate("Configurer", "Ajouter un nouveau Lecteur", 0, QApplication::UnicodeUTF8));
        tBoxConfigLecteur->setItemText(tBoxConfigLecteur->indexOf(page_5), QApplication::translate("Configurer", "Modifier un Lecteur existant", 0, QApplication::UnicodeUTF8));
        tBoxConfigLecteur->setItemText(tBoxConfigLecteur->indexOf(page_6), QApplication::translate("Configurer", "Effacer un Lecteur existant", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("Configurer", "Configurer Lecteur", 0, QApplication::UnicodeUTF8));
        tBoxConfigSuper->setItemText(tBoxConfigSuper->indexOf(page_7), QApplication::translate("Configurer", "Gestion des Vues", 0, QApplication::UnicodeUTF8));
        tBoxConfigSuper->setItemText(tBoxConfigSuper->indexOf(page_8), QApplication::translate("Configurer", "Gestions des Lieux", 0, QApplication::UnicodeUTF8));
        tBoxConfigSuper->setItemText(tBoxConfigSuper->indexOf(page_9), QApplication::translate("Configurer", "Gestion des Zones", 0, QApplication::UnicodeUTF8));
        tBoxConfigSuper->setItemText(tBoxConfigSuper->indexOf(page_13), QApplication::translate("Configurer", "Gestion des Timers", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("Configurer", "Configurer SuPer", 0, QApplication::UnicodeUTF8));
        btAffichage->setText(QApplication::translate("Configurer", "Actualiser l'interface", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Configurer: public Ui_Configurer {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONFIGURER_H
